site_name: Projekt 16
site_description: Dokumentacja programu do przejścia pionkiem po planszy
repo_url: https://github.com/MyNameIsTomek/peojektPracaGrupowa

theme:
  name: material

nav:
  - Strona główna: index.md
  - Opis systemu: opis_systemu.md
  - Przykładowy kod: przykladowy_kod.md
  - Instalacja: instalacja.md
  - Instrukcja użytkownika: instrukcja_uzytkownika.md
  - Konfiguracja: konfiguracja.md
  - Bezpieczeństwo: bezpieczenstwo.md
  - Wdrożenie: wdrozenie.md
